import { useEffect, useState } from 'react'
import { Sparkles, ChevronDown, ChevronUp, Loader2, AlertCircle } from 'lucide-react'
import { generateTenderDossier } from '../lib/gemini'
import { saveTenderDossier } from '../lib/api'

// Renders markdown-like dossier text with basic formatting
function DossierText({ text }) {
  const lines = text.split('\n')
  return (
    <div className="flex flex-col gap-2 text-sm text-ink-900 leading-relaxed">
      {lines.map((line, i) => {
        if (line.startsWith('## ')) {
          return (
            <h3 key={i} className="mt-3 font-display text-base font-semibold text-ink-900 first:mt-0">
              {line.replace('## ', '')}
            </h3>
          )
        }
        if (line.startsWith('- ') || line.startsWith('• ')) {
          return (
            <div key={i} className="flex gap-2">
              <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brass-500" />
              <span>{line.replace(/^[-•]\s/, '')}</span>
            </div>
          )
        }
        if (line.trim() === '') return null
        return <p key={i}>{line}</p>
      })}
    </div>
  )
}

export default function AIDossier({ tender }) {
  const [open, setOpen] = useState(false)
  const [status, setStatus] = useState('idle') // idle | loading | done | error
  const [dossier, setDossier] = useState(tender.ai_dossier || null)
  const [error, setError] = useState('')

  // If we already have a cached dossier in the DB, show it immediately
  useEffect(() => {
    if (tender.ai_dossier) {
      setDossier(tender.ai_dossier)
      setStatus('done')
    }
  }, [tender.ai_dossier])

  async function generate() {
    if (dossier) {
      setOpen((o) => !o)
      return
    }
    setOpen(true)
    setStatus('loading')
    setError('')
    try {
      const text = await generateTenderDossier(tender)
      setDossier(text)
      setStatus('done')
      // Cache in DB (best-effort, don't block UI)
      saveTenderDossier(tender.id, text).catch(() => {})
    } catch (err) {
      setStatus('error')
      setError(err.message)
    }
  }

  const isGeminiMissing = !import.meta.env.VITE_GEMINI_API_KEY

  return (
    <div className="rounded-xl border border-brass-500/30 bg-gradient-to-br from-brass-500/5 to-transparent">
      {/* Header / trigger */}
      <button
        onClick={generate}
        disabled={status === 'loading' || isGeminiMissing}
        className="flex w-full items-center justify-between p-5 text-left"
      >
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brass-500/15">
            {status === 'loading' ? (
              <Loader2 size={16} className="animate-spin text-brass-600" />
            ) : (
              <Sparkles size={16} className="text-brass-600" />
            )}
          </div>
          <div>
            <p className="font-display text-sm font-semibold text-ink-900">
              {status === 'loading' ? 'Generating AI dossier…' : 'AI Tender Dossier'}
            </p>
            <p className="text-xs text-signal-slate">
              {isGeminiMissing
                ? 'Add VITE_GEMINI_API_KEY to .env to enable'
                : dossier
                ? 'AI-generated brief — click to expand'
                : 'Plain-language brief · eligibility snapshot · risk flags'}
            </p>
          </div>
        </div>
        {!isGeminiMissing && (
          <div className="shrink-0 text-signal-slate">
            {open ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </div>
        )}
      </button>

      {/* Content */}
      {open && status === 'done' && dossier && (
        <div className="border-t border-brass-500/20 px-5 pb-5 pt-4">
          <DossierText text={dossier} />
          <p className="mt-4 text-xs text-signal-slate/70">
            Generated by TenderAI · Gemini 2.0 Flash · For guidance only, verify with the official NIT
          </p>
        </div>
      )}

      {open && status === 'error' && (
        <div className="border-t border-brass-500/20 px-5 pb-5 pt-4">
          <div className="flex items-start gap-2 text-sm text-signal-rust">
            <AlertCircle size={15} className="mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        </div>
      )}
    </div>
  )
}
